[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build"

[phases.start]
cmd = "npx serve dist -s -l 3000"

[variables]
NODE_ENV = "production"